# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fad54bca2b7eed3f2b97a478fa115752441a1834350303dcb57a946123127211ef9c152259d08afbf639e106a0a6f95834f62db2285f9666493c8922d91161f

test:
  secret_key_base: fe223c1d7b22313ea418a84eaf72aff52055c041ab830f19b0884af64b36c2dd609d7cad13f35d2d4a76cd5884f23fda199548e1d556acd06dded5a2aeb80cb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
